apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-ingress-host.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: fluxv2-podinfo-demo
      namespace: fluxv2-podinfo-demo