apiVersion: v1
kind: Service
metadata:
  name: fluxv2-podinfo-demo
  namespace: fluxv2-podinfo-demo
  labels:
    app: fluxv2-podinfo-demo
spec:
  type: LoadBalancer
  selector:
    app: fluxv2-podinfo-demo
  ports:
    - port: 80
      targetPort: 9898
      protocol: TCP
