---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxv2-podinfo-demo
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/fluxv2-podinfo-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxv2-demo-app
  targetNamespace: fluxv2-podinfo-demo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: fluxv2-podinfo-demo
      namespace: fluxv2-podinfo-demo
  timeout: 2m
