---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-staging
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxv2-demo-app
  targetNamespace: podinfo
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
  timeout: 2m
