---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxv2-demo-app
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/fabricekrebs/fluxv2-demo-app
  ref:
    branch: main
